name: LogIt
version: 0.4.8.5
author: LucasEasedUp
main: io.github.lucaseasedup.logit.LogItPlugin
softdepend: [Multiverse-Core, Vault]

commands:
  logit:
    description: LogIt generic command.
    usage: /<command> [help|version|reload|backup <force|restore [filename]|remove <amount>>|setwr|gotowr|globalpass <set <password>|remove>|accountcount|ipcount [ip]|config <get <path>|set <path> <value>|list [page]>]

  login:
    description: Logs you in.
    usage: /<command> [password]
    aliases: [l]

  register:
    description: Registers you.
    usage: /<command> <|<password> <confirmpassword>>
    aliases: [reg]

  unregister:
    description: Unregisters you.
    usage: /<command> [password]

  logout:
    description: Logs you out.
    usage: /<command>

  changepass:
    description: Changes your password.
    usage: /<command> <oldpassword> <newpassword> <confirmpassword>

  changeemail:
    description: Changes your e-mail address.
    usage: /<command> <newemail>

  recoverpass:
    description: Recovers your password through e-mail.
    usage: /<command> <email>

permissions:
  logit.*:
    default: false
    children:
      logit.admin: true
  logit.player:
    default: not op
    children:
      logit: true
      logit.help: true
      logit.version: true
      logit.login.self: true
      logit.logout.self: true
      logit.register.self: true
      logit.unregister.self: true
      logit.changepass.self: true
      logit.changeemail.self: true
      logit.recoverpass: true
  logit.mod:
    default: op
    children:
      logit.player: true
      logit.gotowr: true
      logit.login.others: true
      logit.logout.others: true
      logit.register.others: true
      logit.unregister.others: true
      logit.changepass.others: true
      logit.changeemail.others: true
  logit.admin:
    default: false
    children:
      logit.mod: true
      logit.reload: true
      logit.backup.*: true
      logit.setwr: true
      logit.globalpass.*: true
      logit.accountcount: true
      logit.ipcount: true
      logit.config.*: true
  logit:
    default: true
  logit.help:
    default: true
  logit.version:
    default: true
  logit.reload:
    default: false
  logit.backup.*:
    default: false
    children:
      logit.backup.force: true
      logit.backup.restore: true
      logit.backup.remove: true
  logit.backup.force:
    default: false
  logit.backup.restore:
    default: false
  logit.backup.remove:
    default: false
  logit.setwr:
    default: false
  logit.gotowr:
    default: false
  logit.globalpass.*:
    default: false
    children:
      logit.globalpass.set: true
      logit.globalpass.remove: true
  logit.globalpass.set:
    default: false
  logit.globalpass.remove:
    default: false
  logit.accountcount:
    default: false
  logit.ipcount:
    default: false
  logit.config.*:
    default: false
    children:
      logit.config.get: true
      logit.config.set: true
      logit.config.list: true
  logit.config.get:
    default: false
  logit.config.set:
    default: false
  logit.config.list:
    default: false
  logit.login:
    default: false
    children:
      logit.login.self: true
  logit.login.self:
    default: false
  logit.login.others:
    default: false
  logit.logout:
    default: false
    children:
      logit.logout.self: true
  logit.logout.self:
    default: false
  logit.logout.others:
    default: false
  logit.register:
    default: false
    children:
      logit.register.self: true
  logit.register.self:
    default: false
  logit.register.others:
    default: false
  logit.unregister:
    default: false
    children:
      logit.unregister.self: true
  logit.unregister.self:
    default: false
  logit.unregister.others:
    default: false
  logit.changepass:
    default: false
    children:
      logit.changepass.self: true
  logit.changepass.self:
    default: false
  logit.changepass.others:
    default: false
  logit.changeemail.self:
    default: false
  logit.changeemail.others:
    default: false
  logit.recoverpass:
    default: false
  logit.force-login.exempt:
    default: false
  logit.force-login.timeout.exempt:
    default: false
