name: LogIt
version: 0.4.0
author: LucasEasedUp
main: com.gmail.lucaseasedup.logit.LogItPlugin
softdepend: [Multiverse-Core, Vault]
database: true

commands:
  logit:
    description: LogIt generic command.
    usage: /<command> [help|version|reload|purge|backup <force|restore [filename]|remove <amount>>|setwr|gotowr|globalpass <set <password>|remove>]

  login:
    description: Logs you in.
    usage: /<command> <password>
    aliases: [l]

  register:
    description: Registers you.
    usage: /<command> <password> <confirmpassword>
    aliases: [reg]

  unregister:
    description: Unregisters you.
    usage: /<command> <password>

  logout:
    description: Logs you out.
    usage: /<command>

  changepass:
    description: Changes your password.
    usage: /<command> <oldpassword> <newpassword> <confirmpassword>

permissions:
  logit.*:
    default: false
    children:
      logit.admin: true
  logit.player:
    default: not op
    children:
      logit: true
      logit.help: true
      logit.version: true
      logit.login.self: true
      logit.logout.self: true
      logit.register.self: true
      logit.unregister.self: true
      logit.changepass.self: true
  logit.mod:
    default: op
    children:
      logit.player: true
      logit.gotowr: true
      logit.login.others: true
      logit.logout.others: true
      logit.register.others: true
      logit.unregister.others: true
      logit.changepass.others: true
  logit.admin:
    default: false
    children:
      logit.mod: true
      logit.reload: true
      logit.purge: true
      logit.backup.*: true
      logit.setwr: true
      logit.globalpass.*: true
  logit:
    default: true
  logit.help:
    default: true
  logit.version:
    default: true
  logit.reload:
    default: false
  logit.purge:
    default: false
  logit.backup.*:
    default: false
    children:
      logit.backup.force: true
      logit.backup.restore: true
      logit.backup.remove: true
  logit.backup.force:
    default: false
  logit.backup.restore:
    default: false
  logit.backup.remove:
    default: false
  logit.setwr:
    default: false
  logit.gotowr:
    default: false
  logit.globalpass.*:
    default: false
    children:
      logit.globalpass.set: true
      logit.globalpass.remove: true
  logit.globalpass.set:
    default: false
  logit.globalpass.remove:
    default: false
  logit.login:
    default: false
    children:
      logit.login.self: true
  logit.login.self:
    default: false
  logit.login.others:
    default: false
  logit.logout:
    default: false
    children:
      logit.logout.self: true
  logit.logout.self:
    default: false
  logit.logout.others:
    default: false
  logit.register:
    default: false
    children:
      logit.register.self: true
  logit.register.self:
    default: false
  logit.register.others:
    default: false
  logit.unregister:
    default: false
    children:
      logit.unregister.self: true
  logit.unregister.self:
    default: false
  logit.unregister.others:
    default: false
  logit.changepass:
    default: false
    children:
      logit.changepass.self: true
  logit.changepass.self:
    default: false
  logit.changepass.others:
    default: false
  logit.force-login.exempt:
    default: false
  logit.force-login.timeout.exempt:
    default: false
